### ISSUE TITLE
[Question] Config.Meter

### ISSUE THREAD

**Issue by Leslija** [qbcore-framework/qb-taxijob#51]
**Question:**
What does the Config.Meter do exactly?

I decided to extend the script and allow players to edit the price for 100 meters, but then I asked myself a question - Where exactly is Config.Meter calculated? It is only visible in the NUI and is not used in any calculation!

The only value used for the calculation is "fareAmount", which is defined as 6 in the script..

Or do I understand it wrong?

**Comment by tom-osborne** [comment]
I think it's the starting price. When the meter is toggled, it begins from this configured price and then begins to calculate the price from that point based on distance.

**Comment by Leslija** [comment]
![image](https://user-images.githubusercontent.com/19732312/189365100-0f24572a-b883-4b59-8892-7ff3c8b1fc8e.png)
![image](https://user-images.githubusercontent.com/19732312/189365156-5b212de3-d1eb-4d09-a663-239130cff401.png)
![image](https://user-images.githubusercontent.com/19732312/189365241-6d2db8a7-7f9c-4347-b257-9586785bc666.png)

Somehow I can not understand the connection in the screenshots..

The calculation is based on the fareAmount and distance, but not the Config.Meter given price and distance..
Which is distance * 6 like its in formula..

**Comment by tom-osborne** [comment]
Because when you start the meter, it sends the default price. As shown here:
https://github.com/qbcore-framework/qb-taxijob/blob/main/client/main.lua#L420

Then after that is just sends the new calculated price each time.
Every time a new price is sent, it gets added to the previous amount. As shown here: 
https://github.com/qbcore-framework/qb-taxijob/blob/main/html/meter.js#L4

So the first time the meter is updated, it is sent the price in `Config.Meter` then after that it is sent a calculated price from distance travelled. Each time a new price is sent, it is added to the old value.

Hopefully that makes sense.

**Comment by Leslija** [comment]
Okay, freshly installed and drove '2.6mi'..
![image](https://user-images.githubusercontent.com/19732312/189370324-071d7139-5829-4e79-99f8-7b11467b1ef1.png)
does it makes sense?

**Comment by tom-osborne** [comment]
Yeah, it does make sense. You might be right then, perhaps the script isn't doing what it should. I would need to do some testing to work it out.

**Comment by Leslija** [comment]
After you drop an NPC, the counter sets the old values and continues with the new distance..
https://www.youtube.com/watch?v=Y6Worj8tV5o

**Comment by tom-osborne** [comment]
@Leslija This has been addressed in #55 - Would you mind testing and giving feedback?

**Comment by Leslija** [comment]
Sure.
My review is given in the pull request.
